[files]
extend-exclude = [
	# chillerbot-ux
	"scripts/chillerbot_test.sh",
	"src/engine/shared/chillerbot/langparser.cpp",
	# https://github.com/crate-ci/typos/issues/1420
	# https://github.com/crate-ci/typos/issues/1419
	"src/game/client/components/chillerbot/chathelper/check_war_others.cpp",
	"src/game/client/components/chillerbot/chathelper/check_war_self.cpp",
	"src/game/client/components/chillerbot/chathelper/replytoping.cpp",
	"src/game/client/components/chillerbot/chathelper/smalltalk.cpp",
	"src/test/chillerbot.cpp",
	"src/test/langparser.cpp",

	# ddnet
	"build-*/",
	"build/",
	"data/countryflags",
	"data/languages",
	"data/skins",
	"ddnet-libs",
	"other/icons/*.icns",
	"memcheck.supp",
	"scripts/android/files/res",
	"src/engine/external",

	# tests with invalid words
	"src/test/shell_execute.cpp",
	"src/test/str.cpp",
	"src/test/shell_execute_test.cpp",
	"src/test/windows_test.cpp",
	"src/test/str_test.cpp",
]

[default]
extend-ignore-re = [
	# chillerbot-ux
	# https://github.com/crate-ci/typos/issues/1421
	"templeos",

	# ddnet
	'lod',
	'LOD',
	'Lod',
	'PARM',
	'PNGs',
	'SEH',
	'UPnP',
	'Datas',
	'datas',
	'iy',
	'cl_nameplates_ids_seperate_line',
	'LWS_.*_WRITEABLE',
	'0x510E527FUL',
	'I\*\*nteger',
	's\*\*tring',
]
